### ISSUE TITLE
Does it work? Dont you want to add to repo?

### ISSUE THREAD

**Issue by GermanBluefox** [oberstel/iobroker.pjlink#1]

**Comment by oberstel** [comment]
I'm not finished... haven't got the time to work on that project right now. 
Will deploy 0.1 probably between Christmas and New Year. I'll let you now

**Comment by GermanBluefox** [comment]
Thank you.

8 дек. 2017 г. 11:39 пользователь "lob" <notifications@github.com> написал:

**Comment by oberstel** [comment]
It's released now and I created a proper thread on ioBroker forum: http://forum.iobroker.net/viewtopic.php?f=20&t=10201

**Comment by GermanBluefox** [comment]
Perfect :)
