### ISSUE TITLE
Supporting PJLink Class 2 protocol

### ISSUE THREAD

**Issue by Shogun1978** [oberstel/iobroker.pjlink#19]
Is it still planned to be supported? Would be great if class 2 would be supported in the future.

**Comment by oberstel** [comment]
Yes, I‘m working on the next release already... Class II support is in the backlog.

Do you have a proper device to test Class II?

**Comment by Shogun1978** [comment]
Currently not, I will setup a home cinema in our new house. There will be (at least as it looks right now) a beamer from Epson (4k). It will support PJlink2

**Comment by oberstel** [comment]
I'll put it in the feature request list
