### ISSUE TITLE
Please rename repository to ioBroker.pjlink.

### ISSUE THREAD

**Issue by GermanBluefox** [oberstel/iobroker.pjlink#2]
Only repository. Nothing more.

Additionally add tests, like here: https://github.com/ioBroker/ioBroker.template/tree/master/test

And everything from this list :) 
https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-repository

**Comment by oberstel** [comment]
renaming performed successfully ;-)
I will work on the other stuff in two weeks... (family leave)
