### ISSUE TITLE
ESC/VP21 support

### ISSUE THREAD

**Issue by flinke-flasche** [oberstel/iobroker.pjlink#21]
Not an issue.

Do you think about to create an adapter to control the epson projectors with ESC/VP21 protocol.
You can control a lot more than power and the inputs. 

Here you can find the codes
https://files.support.epson.com/pdf/escvp21/escvp21h_20180827.zip

**Comment by oberstel** [comment]
I'll put it in the feature request list

**Comment by oberstel** [comment]
closed for now
