### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [oberstel/iobroker.pjlink#7]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/oberstel/ioBroker.pjlink

- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.pjlink"
- [ ] [E300] Not found on travis. Please setup travis
- [ ] [E604] No "## License" found in README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2019 [object Object]" or "Copyright (c) 20xx-2019 [object Object]" at start of LICENSE

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "pjlink" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by oberstel** [comment]
All issues were fixed
